name: cementerio_app
description: "Aplicación Flutter para gestionar cementerios con autenticación y control de roles."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^32.1.22

  # HTTP y Networking
  http: ^1.1.0
  dio: ^5.3.1

  # Estado y Gestión
  provider: ^6.1.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

  # Almacenamiento Local
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # JWT y Seguridad
  jwt_decoder: ^2.0.1

  # Validación
  email_validator: ^3.0.0

  # UI
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0

  # Navegación
  go_router: ^17.0.1

  # Logging
  logger: ^2.1.0

  flutter_lints: ^6.0.0
  lints: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # lints: ^6.0.0  # (agrega si usas lints directamente)

flutter:
  uses-material-design: true
