name: Deploy React App

on:
  push:
    branches:
      - main  # Se dispara al subir cambios a la rama main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Project
        run: |
          cd cementerio-react
          npm install
          npm run build

      - name: Copy build to Server
        uses: appleboy/scp-action@master
        with:
          host: 192.188.51.84
          username: christian
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "cementerio-react/build/*"
          target: "/var/www/cementerio-app/cementerio-react/build"
          strip_components: 2

      - name: Refresh Nginx Permissions
        uses: appleboy/ssh-action@master
        with:
          host: 192.188.51.84
          username: christian
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo chown -R www-data:www-data /var/www/cementerio-app/cementerio-react/build
            sudo chmod -R 755 /var/www/cementerio-app/cementerio-react/build
            sudo systemctl restart nginx